import { apiClient, ApiResponse } from "./client";

export interface ProjectItem {
  id: string;
  code: string;
  name: string;
  customer: string;
  rabValue: number;
  rapValue: number;
  actualCost: number;
  progress: number;
  status: string;
  manager: string;
  createdAt?: string;
  updatedAt?: string;
}

export interface CreateProjectInput {
  code?: string; // generated by the server when omitted
  name: string;
  customer: string;
  rabValue: number;
  rapValue: number;
  actualCost?: number;
  progress?: number;
  status?: string;
  manager?: string;
}

export const projectsApi = {
  list: async (params?: { page?: number; perPage?: number; search?: string }): Promise<ApiResponse<ProjectItem[]>> => {
    return apiClient<ProjectItem[]>("/projects", { params });
  },

  getById: async (id: string): Promise<ApiResponse<ProjectItem>> => {
    return apiClient<ProjectItem>(`/projects/${id}`);
  },

  create: async (data: CreateProjectInput): Promise<ApiResponse<ProjectItem>> => {
    return apiClient<ProjectItem>("/projects", {
      method: "POST",
      body: JSON.stringify(data),
    });
  },

  update: async (id: string, data: Partial<CreateProjectInput>): Promise<ApiResponse<ProjectItem>> => {
    return apiClient<ProjectItem>(`/projects/${id}`, {
      method: "PUT",
      body: JSON.stringify(data),
    });
  },

  delete: async (id: string): Promise<ApiResponse<null>> => {
    return apiClient<null>(`/projects/${id}`, {
      method: "DELETE",
    });
  },

  // recalculate derives real Progress (completed / total Kanban tasks) and
  // ActualCost (sum of timesheet hours x hourly rate) from actual task and
  // timesheet data, instead of relying on the manually-edited fields.
  recalculate: async (id: string): Promise<ApiResponse<ProjectItem>> => {
    return apiClient<ProjectItem>(`/projects/${id}/recalculate`, {
      method: "POST",
    });
  },
};

export interface TimeEntryItem {
  id: string;
  projectCode: string;
  taskTitle: string;
  workerName: string;
  date: string;
  durationMinutes: number;
  hourlyRate: number;
  isBillable: boolean;
  createdAt?: string;
}

export interface CreateTimeEntryInput {
  projectCode: string;
  taskTitle?: string;
  workerName?: string;
  date?: string;
  durationMinutes: number;
  hourlyRate?: number;
  isBillable?: boolean;
}

export const timeEntriesApi = {
  list: async (params?: { page?: number; perPage?: number; projectCode?: string }): Promise<ApiResponse<TimeEntryItem[]>> => {
    return apiClient<TimeEntryItem[]>("/projects/time-entries", { params });
  },

  create: async (data: CreateTimeEntryInput): Promise<ApiResponse<TimeEntryItem>> => {
    return apiClient<TimeEntryItem>("/projects/time-entries", {
      method: "POST",
      body: JSON.stringify(data),
    });
  },
};
