"use client";

import * as React from "react";
import Link from "next/link";
import {
  FolderKanban,
  Plus,
  Search,
  Filter,
  Download,
  Building,
  Calendar,
  CheckCircle2,
  Clock,
  ArrowUpRight,
  TrendingUp,
} from "lucide-react";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Card, CardContent } from "@/components/ui/card";
import { DataTable, Column } from "@/components/data-table/data-table";
import { MoneyDisplay } from "@/components/shared/money-display";
import { downloadCsv } from "@/lib/utils/csv";
import {
  Dialog,
  DialogContent,
  DialogHeader,
  DialogTitle,
  DialogFooter,
} from "@/components/ui/dialog";

interface ProjectItem {
  id: string;
  code: string;
  name: string;
  customer: string;
  rabValue: number; // Rencana Anggaran Biaya (Income / Target)
  rapValue: number; // Rencana Anggaran Proyek (Cost Budget)
  actualCost: number; // Realisasi Pengeluaran
  progress: number;
  status: "Planning" | "In Progress" | "On Hold" | "Completed";
  startDate: string;
  endDate: string;
  manager: string;
}

import { projectsApi, ProjectItem as ApiPrj } from "@/lib/api/projects";
import { useAppStore } from "@/stores/app-store";

export default function ProjectsPage() {
  const { currentUser } = useAppStore();
  const [projects, setProjects] = React.useState<ProjectItem[]>([]);
  const [loadError, setLoadError] = React.useState<string | null>(null);
  const [formError, setFormError] = React.useState<string | null>(null);
  const [notice, setNotice] = React.useState<string | null>(null);
  const [isLoading, setIsLoading] = React.useState(true);
  const [search, setSearch] = React.useState("");
  const [isNewProjectOpen, setIsNewProjectOpen] = React.useState(false);
  const [recalculatingId, setRecalculatingId] = React.useState<string | null>(null);

  // Form State
  const [projectName, setProjectName] = React.useState("");
  const [customer, setCustomer] = React.useState("");
  const [rab, setRab] = React.useState(500000000);
  const [rap, setRap] = React.useState(380000000);

  const handleDownloadPortfolioReport = () => {
    downloadCsv(
      "project-portfolio-report.csv",
      ["Code", "Name", "Customer", "RAB", "RAP", "Actual Cost", "Progress", "Status", "Start Date", "End Date", "Manager"],
      projects.map((p) => [
        p.code,
        p.name,
        p.customer,
        p.rabValue,
        p.rapValue,
        p.actualCost,
        `${p.progress}%`,
        p.status,
        p.startDate,
        p.endDate,
        p.manager,
      ])
    );
  };

  const fetchProjects = () => {
    projectsApi
      .list()
      .then((res) => {
                  const mapped: ProjectItem[] = (res.data || []).map((p: ApiPrj) => ({
            id: p.id,
            code: p.code,
            name: p.name,
            customer: p.customer,
            rabValue: p.rabValue,
            rapValue: p.rapValue,
            actualCost: p.actualCost,
            progress: p.progress,
            status: (p.status as ProjectItem["status"]) || "Planning",
            startDate: p.createdAt ? p.createdAt.slice(0, 10) : "-",
            endDate: "-",
            manager: p.manager || "-",
          }));
          setProjects(mapped);
      })
      .catch((err) => {
        console.error("Failed to load projects", err);
        setLoadError("Gagal memuat data proyek dari server.");
      })
      .finally(() => {
        setIsLoading(false);
      });
  };

  React.useEffect(() => {
    fetchProjects();
  }, []);

  // Recalculates real Progress (completed / total Kanban tasks) and
  // ActualCost (sum of logged timesheet hours x hourly rate) from actual
  // task/timesheet data, instead of relying on stale manually-edited
  // fields (see modules/project.RecalculateProgress on the backend).
  const handleRecalculate = async (id: string) => {
    setRecalculatingId(id);
    try {
      const res = await projectsApi.recalculate(id);
      if (res.data) {
        setProjects((prev) =>
          prev.map((p) =>
            p.id === id ? { ...p, progress: res.data.progress, actualCost: res.data.actualCost } : p
          )
        );
      }
    } catch (err) {
      setNotice(err instanceof Error ? err.message : "Gagal menghitung ulang progress proyek.");
    } finally {
      setRecalculatingId(null);
    }
  };

  const filtered = projects.filter(
    (p) =>
      p.name.toLowerCase().includes(search.toLowerCase()) ||
      p.code.toLowerCase().includes(search.toLowerCase()) ||
      p.customer.toLowerCase().includes(search.toLowerCase())
  );

  const handleCreateProject = async (e: React.FormEvent) => {
    e.preventDefault();
    if (!projectName || !customer) return;
    setFormError(null);

    try {
      // The project code is generated by the server.
      await projectsApi.create({
        name: projectName,
        customer,
        rabValue: Number(rab) || 0,
        rapValue: Number(rap) || 0,
        actualCost: 0,
        progress: 0,
        status: "Planning",
        manager: currentUser.name,
      });
      fetchProjects();
      setIsNewProjectOpen(false);
      setProjectName("");
      setCustomer("");
    } catch (err) {
      setFormError(err instanceof Error ? err.message : "Gagal menyimpan proyek.");
    }
  };

  const totalRAB = projects.reduce((acc, curr) => acc + curr.rabValue, 0);
  const totalActual = projects.reduce((acc, curr) => acc + curr.actualCost, 0);

  const columns: Column<ProjectItem>[] = [
    {
      key: "code",
      header: "Kode & Nama Proyek",
      render: (row) => (
        <Link href={`/projects/${row.id}`} className="block hover:opacity-80">
          <span className="font-mono font-bold text-brand-dark text-xs">{row.code}</span>
          <div className="font-bold text-foreground text-xs mt-0.5 hover:underline">{row.name}</div>
          <div className="text-[11px] text-muted-foreground flex items-center gap-1 mt-0.5">
            <Building className="h-3 w-3 text-muted-foreground" />
            {row.customer}
          </div>
        </Link>
      ),
    },
    {
      key: "rabValue",
      header: "Kontrol RAB & RAP",
      render: (row) => {
        const margin = row.rabValue - row.rapValue;
        return (
          <div className="space-y-0.5 text-xs">
            <div className="flex justify-between gap-2">
              <span className="text-muted-foreground">RAB (Nilai):</span>
              <span className="font-bold text-foreground"><MoneyDisplay amount={row.rabValue} /></span>
            </div>
            <div className="flex justify-between gap-2">
              <span className="text-muted-foreground">RAP (Pagu):</span>
              <span className="font-semibold text-slate-700"><MoneyDisplay amount={row.rapValue} /></span>
            </div>
            <div className="text-[10px] text-emerald-600 font-bold">
              Est. Margin: <MoneyDisplay amount={margin} /> ({Math.round((margin / row.rabValue) * 100)}%)
            </div>
          </div>
        );
      },
    },
    {
      key: "actualCost",
      header: "Realisasi Biaya",
      render: (row) => {
        const percent = Math.round((row.actualCost / row.rapValue) * 100) || 0;
        return (
          <div className="space-y-1 text-xs">
            <div className="font-bold text-foreground">
              <MoneyDisplay amount={row.actualCost} />
            </div>
            <div className="text-[11px] text-muted-foreground">
              {percent}% dari Pagu RAP
            </div>
          </div>
        );
      },
    },
    {
      key: "progress",
      header: "Progres Fisik",
      render: (row) => (
        <div className="w-32 space-y-1">
          <div className="flex justify-between text-xs font-bold">
            <span>{row.progress}%</span>
          </div>
          <div className="h-2 w-full bg-slate-100 rounded-full overflow-hidden">
            <div
              className="h-full bg-brand-primary rounded-full transition-all"
              style={{ width: `${row.progress}%` }}
            />
          </div>
        </div>
      ),
    },
    {
      key: "status",
      header: "Status",
      render: (row) => {
        const styles: Record<string, string> = {
          Planning: "bg-blue-50 text-blue-700 border-blue-200",
          "In Progress": "bg-amber-50 text-amber-700 border-amber-200",
          "On Hold": "bg-rose-50 text-rose-700 border-rose-200",
          Completed: "bg-emerald-50 text-emerald-700 border-emerald-200",
        };
        return (
          <span className={`px-2.5 py-0.5 rounded-full text-[10px] font-bold border ${styles[row.status]}`}>
            {row.status}
          </span>
        );
      },
    },
    {
      key: "manager",
      header: "Project Manager",
      render: (row) => (
        <span className="text-xs font-medium text-foreground">{row.manager}</span>
      ),
    },
    {
      key: "id",
      header: "Progres Real",
      render: (row) => (
        <div className="flex items-center gap-1.5">
          <Button
            size="sm"
            variant="outline"
            disabled={recalculatingId === row.id}
            onClick={() => handleRecalculate(row.id)}
            className="h-7 px-2 text-[11px] font-bold gap-1"
            title="Hitung ulang progress (dari tugas Kanban selesai) dan biaya aktual (dari timesheet) yang sebenarnya"
          >
            {recalculatingId === row.id ? "Menghitung..." : "Recalculate"}
          </Button>
          <Button asChild size="sm" variant="ghost" className="h-7 px-2 text-[11px] font-bold gap-1">
            <Link href={`/projects/${row.id}`}>
              Detail <ArrowUpRight className="h-3 w-3" />
            </Link>
          </Button>
        </div>
      ),
    },
  ];

  return (
    <div className="space-y-6">
      {/* Header */}
      <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-4">
        <div>
          <h1 className="text-2xl font-black tracking-tight text-foreground flex items-center gap-2">
            <FolderKanban className="h-6 w-6 text-brand-primary" />
            <span>Manajemen Proyek & Kontrol Anggaran (RAB/RAP)</span>
          </h1>
          <p className="text-xs sm:text-sm text-muted-foreground">
            Pantau kontrak proyek, estimasi anggaran RAB, pagu biaya RAP, realisasi pengeluaran, dan progres fisik.
          </p>
        </div>

        <div className="flex items-center gap-2">
          <Button
            variant="outline"
            size="sm"
            onClick={handleDownloadPortfolioReport}
            className="h-9 gap-1.5 text-xs border-border"
          >
            <Download className="h-3.5 w-3.5 text-muted-foreground" />
            <span>Ekspor RAB/RAP</span>
          </Button>

          <Button
            variant="gradient"
            size="sm"
            onClick={() => setIsNewProjectOpen(true)}
            className="h-9 gap-1.5 text-xs font-bold"
          >
            <Plus className="h-3.5 w-3.5" />
            <span>Buat Proyek Baru</span>
          </Button>
        </div>
      </div>

      {/* KPI Cards */}
      <div className="grid grid-cols-1 sm:grid-cols-3 gap-4">
        <Card className="border-border shadow-2xs">
          <CardContent className="p-4 space-y-1">
            <span className="text-xs text-muted-foreground font-semibold">Total Nilai Kontrak Portofolio (RAB)</span>
            <div className="text-2xl font-black text-brand-dark">
              <MoneyDisplay amount={totalRAB} />
            </div>
            <span className="text-[11px] text-muted-foreground">{projects.length} Proyek Terdaftar</span>
          </CardContent>
        </Card>

        <Card className="border-border shadow-2xs">
          <CardContent className="p-4 space-y-1">
            <span className="text-xs text-muted-foreground font-semibold">Realisasi Biaya Aktual Terpakai</span>
            <div className="text-2xl font-black text-brand-indigo">
              <MoneyDisplay amount={totalActual} />
            </div>
            <span className="text-[11px] text-emerald-600 font-semibold flex items-center gap-1">
              <CheckCircle2 className="h-3.5 w-3.5" /> Terkendali di Bawah Pagu RAP
            </span>
          </CardContent>
        </Card>

        <Card className="border-border shadow-2xs">
          <CardContent className="p-4 space-y-1">
            <span className="text-xs text-muted-foreground font-semibold">Rata-Rata Progres Proyek</span>
            <div className="text-2xl font-black text-emerald-600">62.5%</div>
            <span className="text-[11px] text-muted-foreground">Sesuai Milestone Timeline</span>
          </CardContent>
        </Card>
      </div>

      {/* Table */}
      <div className="bg-white rounded-xl border border-border shadow-xs overflow-hidden space-y-3 p-4">
        <div className="flex items-center gap-2 max-w-sm">
          <Search className="h-3.5 w-3.5 text-muted-foreground" />
          <Input
            placeholder="Cari proyek, kode, klien..."
            value={search}
            onChange={(e) => setSearch(e.target.value)}
            className="h-8 text-xs"
          />
        </div>

{loadError && (
          <div role="alert" className="m-3 px-3 py-2 rounded-lg bg-rose-50 border border-rose-200 text-xs text-rose-700">
            {loadError}
          </div>
        )}
        {notice && (
          <div role="alert" className="m-3 px-3 py-2 rounded-lg bg-rose-50 border border-rose-200 text-xs text-rose-700">
            {notice}
          </div>
        )}
        {isLoading ? (
          <div className="py-10 text-center text-xs text-muted-foreground">Memuat data...</div>
        ) : (
          <DataTable data={filtered} columns={columns} />
        )}
      </div>

      {/* Modal Buat Proyek Baru */}
      <Dialog open={isNewProjectOpen} onOpenChange={setIsNewProjectOpen}>
        <DialogContent className="max-w-md">
          <DialogHeader>
            <DialogTitle className="text-base font-bold flex items-center gap-2">
              <Plus className="h-4 w-4 text-brand-primary" />
              <span>Inisiasi Proyek & RAB/RAP Baru</span>
            </DialogTitle>
          </DialogHeader>

          <form onSubmit={handleCreateProject} className="space-y-3.5 text-xs text-left">
            {formError && (
              <div role="alert" className="px-3 py-2 rounded-lg bg-rose-50 border border-rose-200 text-xs text-rose-700">
                {formError}
              </div>
            )}
            <div className="space-y-1">
              <label className="font-bold text-foreground">Nama Proyek *</label>
              <Input
                placeholder="Contoh: Pengadaan Pallet Racking Hub Bekasi"
                value={projectName}
                onChange={(e) => setProjectName(e.target.value)}
                required
                className="h-9 text-xs"
              />
            </div>

            <div className="space-y-1">
              <label className="font-bold text-foreground">Klien / Akun Terkait *</label>
              <Input
                placeholder="Contoh: PT Sentosa Logistik"
                value={customer}
                onChange={(e) => setCustomer(e.target.value)}
                required
                className="h-9 text-xs"
              />
            </div>

            <div className="grid grid-cols-1 sm:grid-cols-2 gap-2.5">
              <div className="space-y-1">
                <label className="font-bold text-foreground">Nilai Kontrak RAB (IDR)</label>
                <Input
                  type="number"
                  value={rab}
                  onChange={(e) => setRab(Number(e.target.value))}
                  className="h-9 text-xs"
                />
              </div>

              <div className="space-y-1">
                <label className="font-bold text-foreground">Pagu Biaya RAP (IDR)</label>
                <Input
                  type="number"
                  value={rap}
                  onChange={(e) => setRap(Number(e.target.value))}
                  className="h-9 text-xs"
                />
              </div>
            </div>

            <DialogFooter className="pt-2">
              <Button
                type="button"
                variant="outline"
                size="sm"
                onClick={() => setIsNewProjectOpen(false)}
                className="h-9 text-xs"
              >
                Batal
              </Button>
              <Button type="submit" variant="gradient" size="sm" className="h-9 text-xs font-bold">
                Simpan Proyek
              </Button>
            </DialogFooter>
          </form>
        </DialogContent>
      </Dialog>
    </div>
  );
}
