/**
 * Human-readable description of a finance record's `sourceDoc` key.
 *
 * The backend tags journal entries, receivables and payables that it creates
 * automatically with a key like "sales-invoice:<uuid>". Records entered by
 * hand have an empty (or free-text) sourceDoc.
 */
export interface SourceInfo {
  label: string;
  /** True when the record was generated by another module, not typed in. */
  auto: boolean;
}

const SOURCE_LABELS: Record<string, string> = {
  "sales-invoice": "Sales Invoice",
  "sales-invoice-payment": "Sales Invoice Payment",
  "purchase-invoice": "Purchase Invoice",
  "purchase-invoice-payment": "Purchase Invoice Payment",
  "purchase-dp": "Purchase Down Payment",
  "payroll-accrual": "Payroll",
  "payroll-payment": "Payroll Payment",
  "reimbursement-approval": "Reimbursement",
  "reimbursement-payment": "Reimbursement Payment",
};

export function describeSource(sourceDoc?: string | null): SourceInfo {
  if (!sourceDoc) return { label: "Manual", auto: false };
  const prefix = sourceDoc.split(":")[0];
  const label = SOURCE_LABELS[prefix];
  return label ? { label, auto: true } : { label: sourceDoc, auto: false };
}
